language: c

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];  sudo apt-get update                                     ; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];  sudo apt-get install -y build-essential gcc-multilib gcc-arm-embedded g++-multilib ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; bash -x .install_gcc_arm_embedded_osx.sh ; fi

script:
    - mkdir travis_build
    - cd travis_build
    - cmake -G "Unix Makefiles" ..
    - make

os:
- linux
- osx

